version: '3.8'

services:
  # Neon Local proxy for development
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      # Persist branch metadata for Git integration
      - ./.neon_local:/tmp/.neon_local
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    networks:
      - acquisitions-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Node.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env.development
    volumes:
      # Mount source code for development hot-reload
      - .:/app
      - /app/node_modules
      # Mount logs directory
      - ./logs:/app/logs
    depends_on:
      neon-local:
        condition: service_healthy
    networks:
      - acquisitions-dev
    restart: unless-stopped

networks:
  acquisitions-dev:
    driver: bridge